name: CI Checks

on:
  label:
    types: [created, edited]
  pull_request:
    branches: ['main', 'develop']

env:
  PROJECT_NAME: "tracker-go"
  GO_DIRECTORY: "./go"
  GO_VERSION: 1.24.4

jobs:
  build:
    name: CI Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 
        uses: actions/setup-go@v5
        with:
          go-version: ${{env.GO_VERSION}}

      - name: Install Dependencies
        run: go get .

      - name: Build Go
        run: go build .
